version: 2.1
commands:
    install_make:
        steps:
            - run:
                name: Install make
                command: apk add make
    composer_install:
        steps:
            - run:
                name: Download composer
                command: |
                    curl --location https://getcomposer.org/composer.phar -o /usr/local/bin/composer
                    chmod +x /usr/local/bin/composer
            - run:
                name: Install composer
                command: |
                    composer install --no-interaction --no-progress
                    composer require --dev friendsofphp/php-cs-fixer ^2.14
                    composer require --dev phpstan/phpstan ^0.11.2
                    composer require --dev phpunit/phpunit ^8.0

jobs:
    phpcs:
        docker:
            - image: php:7.2-cli-alpine
        working_directory: ~/repo
        steps:
            - checkout
            - install_make
            - composer_install
            - run: make cs

    phpstan:
        docker:
            - image: php:7.2-cli-alpine
        working_directory: ~/repo
        steps:
            - checkout
            - install_make
            - composer_install
            - run: make stan

    phpunit:
        docker:
            - image: php:7.2-cli-alpine
        working_directory: ~/repo
        steps:
            - checkout
            - install_make
            - composer_install
            - run: make unit

workflows:
    version: 2.1
    commit:
        jobs:
            - phpcs
            - phpstan
            - phpunit
